language: go
dist: trusty

go:
- 1.12.x

env:
  global:
    - GO111MODULE=on

# Don't email me the results of the test runs.
notifications:
  email: false


# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - make build
